// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AssignautomatictraningTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void assignautomatictraning() {
    driver.get("https://test.taskmasterpro.com/qmrp.php?lc=1");
    driver.manage().window().setSize(new Dimension(1296, 696));
    {
      WebElement element = driver.findElement(By.id("menu"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("menu"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("menu"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.linkText("Human Resources")).click();
    driver.findElement(By.linkText("Training Manager (Library)")).click();
    driver.findElement(By.cssSelector("label > input")).click();
    driver.findElement(By.cssSelector("label > input")).sendKeys("such");
    driver.findElement(By.cssSelector(".odd:nth-child(1) .btn-default")).click();
    driver.switchTo().frame(0);
    driver.findElement(By.cssSelector(".select2-search-choice:nth-child(2) > .select2-search-choice-close")).click();
    driver.findElement(By.cssSelector(".select2-search-choice-close")).click();
    driver.findElement(By.id("staffButton")).click();
    driver.findElement(By.id("recurring")).click();
    {
      WebElement dropdown = driver.findElement(By.id("recurring"));
      dropdown.findElement(By.xpath("//option[. = 'Monthly']")).click();
    }
    driver.findElement(By.id("auto_type_region")).click();
    driver.findElement(By.id("s2id_autogen2")).click();
    driver.findElement(By.id("all_user_levels")).click();
    driver.findElement(By.id("saveButton")).click();
    driver.switchTo().defaultContent();
    assertThat(driver.getTitle(), is("Training Manager (Library) | TaskMaster Pro v96907b3"));
    driver.close();
  }
}
